# Generated by Django 4.2.7 on 2023-11-04 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_user_rename_about_killer_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUsers',
        ),
    ]
