# Generated by Django 4.2.7 on 2023-11-04 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_rename_user_appusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUsers',
            new_name='AppUser',
        ),
    ]
