# Generated by Django 4.2.7 on 2023-11-04 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_appuser_killer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='killer',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.killer'),
        ),
    ]
