# Generated by Django 4.2.7 on 2023-11-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_killer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killer',
            name='user',
            field=models.ManyToManyField(blank=True, to='project_app.appuser'),
        ),
    ]
