# Generated by Django 4.2.7 on 2023-11-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0012_alter_appuser_killer_alter_killer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='killer',
            name='photo',
            field=models.ImageField(default=None, upload_to='killers'),
        ),
    ]
