# Generated by Django 4.2.7 on 2023-11-04 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_rename_appusers_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='killer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_app.killer'),
        ),
    ]
