# Generated by Django 4.2.7 on 2023-11-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_remove_appuser_killer'),
    ]

    operations = [
        migrations.AddField(
            model_name='killer',
            name='user',
            field=models.ManyToManyField(to='project_app.appuser'),
        ),
    ]
