# Generated by Django 4.2.7 on 2023-11-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0011_remove_killer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='killer',
            field=models.ManyToManyField(related_name='users', to='project_app.killer'),
        ),
        migrations.AlterField(
            model_name='killer',
            name='description',
            field=models.TextField(),
        ),
    ]
